config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :posts
      resources :admin_users

      root to: "users#index"
    end
  resources :posts
  devise_for :users, skip: [:registrations]
  root to: "static#home"
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: { submitted: 0, approved: 1, rejected: 2 }
  belongs_to :user
  validates_presence_of :date, :rationale
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :first_name, :last_name 

  def full_name 
    first_name.capitalize + " " + last_name.capitalize
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  def self.admin_types
    ['AdminUser']
  end

  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!, :authenticate_admin

    def authenticate_admin
      unless Admin.admin_types.include?(current_user.try(:type))
        flash[:alert] = "You are not authorized to access this page."
        redirect_to(root_path)
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post, notice: "post created"
    else
      render :new
    end
  end

  def edit
    authorize @post
  end

  def update
    authorize @post
    if @post.update(post_params)
      redirect_to @post, notice: "post updated"
    else
      render :edit
    end
  end

  def destroy
    @post.delete
    redirect_to posts_path, notice: "post deleted"
  end

  def show
  end

  private
  def post_params
    params.require(:post).permit(:date, :rationale, :status)
  end
  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_current_path?(path)
    "active" if current_page?(path)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Overtime</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= render 'shared/nav'%>
        <%= yield %>
      </div>
    </div>
  </div>

<%= render 'shared/alerts' %>
</body>

</html>

app/views/posts/_form.html.erb
<%= form_for(@post, class: "form") do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Overtime App Notification", stick: false) %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_field :date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :rationale %>
    <%= f.text_area :rationale, class: "form-control" %>
  </div>
  <%= render partial: 'status', locals: { f: f } if current_user.type == "AdminUser" %>
  <%= f.submit "Save", class:"btn btn-primary", type:"submit" %>

<% end %>

app/views/posts/_post.html.erb
<tr>
  <td>
    <%= post.id %>
  </td>
  <td>
    <%= post.created_at.strftime("%b/%d/%Y") %>
  </td>
  <td>
    <%= post.user.full_name %>
  </td>
  <td>
    <%= truncate(post.rationale,  length: 15) %>
  </td>
  <td>
    <%= link_to "Edit", edit_post_path(post), id: "edit_post_#{post.id}" %>
  </td>
  <td>
    <%= link_to "Delete", post_path(post), method: :delete, id: "delete_post_#{post.id}_from_index" %>
  </td>
</tr>

app/views/posts/_status.html.erb
<div class="form-group">
  <%= f.label :status, 'Submitted' %>
  <%= f.radio_button :status, 'submitted'%>
  <%= f.label :status, 'Approved' %>
  <%= f.radio_button :status, 'approved'%>
  <%= f.label :status, 'Rejected' %>
  <%= f.radio_button :status, 'rejected'%>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= render  'form' %>

app/views/posts/index.html.erb
<div class="post-index">
  <h1>Posts index</h1>

    <table class="table table-hover table-sm table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Date</th>
          <th>User</th>
          <th>Rationale</th>
          <th>Option</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <%= render @posts %>
      </tbody>
    </table>
</div>

app/views/posts/new.html.erb
<h1>Create post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= @post.inspect %>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Overtime App Alert", sticky: false) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Overtime App Error", sticky: false) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Overtime App Notification", sticky: false) %>
<% end %>

app/views/shared/_nav.html.erb
<div class="page-header mb-4">
  <h1>
    Page Title <small>-woah so fast to make layout</small>
  </h1>
  <p>Made with <a href="https://www.layoutit.com/">LayoutIt</a></p>
</div>

<% if current_user %>
  <ul class="nav nav-tabs custom-nav mb-1">
    <li class="nav-item">
      <%= link_to "Home", root_path, class:"nav-link #{is_current_path?(root_path)}" %>
    </li>
    <li class="nav-item">
      <%= link_to "Post", posts_path, class:"nav-link #{is_current_path?(posts_path)}" %>
    </li>
    <li class="nav-item">
      <%= link_to "New Post", new_post_path, class:"nav-link #{is_current_path?(new_post_path)}", id: "new_post_from_nav"%>
    </li>
    <li class="nav-item dropdown ml-md-auto">
      <span class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown">Options</span>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
        <% if current_user.type == "AdminUser" %>
          <%= link_to "Admin Dashboard", admin_root_path, class:"dropdown-item" %>
        <% end %>
        <%= link_to "Logout", destroy_user_session_path, class:"dropdown-item", method: :delete %>
      </div>
    </li>
  </ul>
<% end %>